#!/bin/bash

cho "argument 1 is "$1

if [ $2 == 'test' ]; then
echo "argument 2 is "$2
fi
echo "argument 1 is "$1

if [ -z $2 ]; then
echo "argument 2 is empty"
fi
echo "argument 1 is "$1

if [ -z $2 ];
then
echo "argument 2 is empty"
else
echo "argument 2 is "$2
fi
